import Footer from '@/components/footer'
import Header from '@/components/header'
import LayoutWrapper from '@/components/layoutWrapper'

import { NotoSansJP } from '@/constants/font'

import type { Metadata } from 'next'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body className={`${NotoSansJP.className} bg-[#f2f2f2] text-[#333]`}>
        <Header />
        <LayoutWrapper>
          <div>{children}</div>
        </LayoutWrapper>
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout
