import { Sawarabi_Gothic } from 'next/font/google'

import Header from '@/components/header'
import LayoutWrapper from '@/components/layoutWrapper'

import type { Metadata } from 'next'

import '@/styles/globals.css'

const SawarabiGothic = Sawarabi_Gothic({
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body className={`${SawarabiGothic.className} bg-[#eaebe8] text-[#333]`}>
        <Header />
        <LayoutWrapper>
          <div>{children}</div>
        </LayoutWrapper>
      </body>
    </html>
  )
}

export default RootLayout
