import { GoogleAnalytics } from '@next/third-parties/google'
import NextTopLoader from 'nextjs-toploader'

import Footer from '@/component/layout/footer'
import Header from '@/component/layout/header'
import { gaId } from '@/config'
import { mPlusRounded1c400 } from '@/constant/font'

import type { Metadata } from 'next'

import '@/style/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body
        className={`${mPlusRounded1c400.className} min-h-dvh max-w-7xl mx-auto bg-slate-100 dark:bg-slate-900 dark:text-gray-200 transition-colors duration-200`}
      >
        <NextTopLoader color="#e30613" showSpinner={false} />
        <Header />
        <div className="p-8">{children}</div>
        <Footer />
      </body>
      <GoogleAnalytics gaId={gaId} />
    </html>
  )
}
