name: Release (dev → main)

on:
  push:
    branches: [development]

# bot がブランチを push する
permissions:
  contents: write

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm

      - run: npm ci

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: "chore: version packages"
          title:  "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
